# Generated by Django 5.0.3 on 2024-03-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0002_auto_20240305_1727'),
    ]

    operations = [
    ]
