# Generated by Django 5.0.3 on 2024-03-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('carbon_io_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('carbon_io_id', models.CharField(max_length=36)),
                ('year', models.DateTimeField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclemake')),
            ],
        ),
    ]
