# Generated by Django 5.0.3 on 2024-03-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemake',
            old_name='carbon_io_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='carbon_io_id',
            new_name='uuid',
        ),
    ]
