# Generated by Django 5.0.3 on 2024-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_carbon_io_id_vehiclemake_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
