# Generated by Django 5.0.3 on 2024-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distanceunit',
            name='symbol',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
