# Generated by Django 5.0.3 on 2024-03-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceunit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='distanceunit',
            name='symbol',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
