# Generated by Django 5.0.3 on 2024-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_estimator', '0002_distanceunit_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceunit',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
