# Generated by Django 5.0.3 on 2024-03-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_estimator', '0002_alter_distanceunit_name_alter_distanceunit_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewableemissionestimates',
            unique_together={('user_id', 'emissions_estimate')},
        ),
    ]
