# Generated by Django 5.0.3 on 2024-03-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions_estimator', '0003_alter_viewableemissionestimates_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewableemissionestimates',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='viewableemissionestimates',
            unique_together={('user', 'emissions_estimate')},
        ),
    ]
