# Generated by Django 5.0.3 on 2024-03-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_makes', '0001_initial'),
    ]

    operations = [
    ]
